import { getAvatarPalette } from '@oneworks/avatar'
// Display translations only; palette identity and rendering are supplied by Avatar.
const names: Record<string,string> = {
  tabby:'狸花',white:'纯白',gold:'金色',cocoa:'可可',siamese:'暹罗', 'british-shorthair':'英国短毛','russian-blue':'俄罗斯蓝猫','orange-tabby':'橘猫','cow-cat':'奶牛猫','black-cat':'黑猫',
  'shiba-inu':'柴犬',husky:'哈士奇',corgi:'柯基','golden-retriever':'金毛','border-collie':'边境牧羊犬',dalmatian:'大麦町',
  'holland-lop':'荷兰垂耳','netherland-dwarf':'荷兰侏儒兔','dutch-rabbit':'荷兰兔','himalayan-rabbit':'喜马拉雅兔','lionhead-rabbit':'狮子兔','english-spot':'英国斑点兔',
  'brown-bear':'棕熊','polar-bear':'北极熊','asian-black-bear':'亚洲黑熊','giant-panda':'大熊猫','spectacled-bear':'眼镜熊','sun-bear':'马来熊','red-panda':'小熊猫',koala:'考拉',raccoon:'浣熊',wombat:'袋熊','teddy-bear':'泰迪熊',
  'syrian-hamster':'金丝熊','pudding-hamster':'布丁仓鼠','silver-fox-hamster':'银狐仓鼠','sapphire-hamster':'蓝宝石仓鼠',
  capybara:'原色水豚','sandy-capybara':'沙色水豚','dark-capybara':'深棕水豚','capybara-pup':'水豚宝宝',
  'sea-otter':'海獭','river-otter':'河獭','asian-small-clawed-otter':'亚洲小爪水獭',
  'pink-pig':'粉红小猪','black-pig':'黑猪','spotted-pig':'斑点猪','wild-boar':'野猪',
  'sika-deer':'梅花鹿',reindeer:'驯鹿','white-deer':'白鹿','deer-fawn':'小鹿宝宝',
  'white-sheep':'白绵羊','black-faced-sheep':'黑脸羊','horned-ram':'卷角羊',lamb:'羊羔','mountain-goat':'山羊',
  'cream-alpaca':'奶油羊驼','caramel-alpaca':'焦糖羊驼','gray-alpaca':'灰羊驼','alpaca-cria':'羊驼宝宝',
  'dairy-cow':'黑白奶牛','jersey-cow':'娟姗牛','highland-cow':'高地牛','cow-calf':'小牛犊',
  'red-squirrel':'红松鼠','gray-squirrel':'灰松鼠',chipmunk:'花栗鼠','black-squirrel':'黑松鼠',
  'bengal-tiger':'孟加拉虎','white-tiger':'白虎','golden-tiger':'金虎','tiger-cub':'小虎崽',
  'african-lion':'非洲狮',lioness:'母狮','white-lion':'白狮','lion-cub':'小狮子',
  'european-hedgehog':'欧洲刺猬','cream-hedgehog':'奶油刺猬','albino-hedgehog':'白化刺猬','cinnamon-hedgehog':'肉桂刺猬',
  'harbor-seal':'港海豹','harp-seal':'竖琴海豹','gray-seal':'灰海豹','seal-pup':'海豹宝宝',
  'north-american-beaver':'北美河狸','eurasian-beaver':'欧亚河狸','dark-beaver':'深色河狸','beaver-kit':'河狸宝宝',
  'american-guinea-pig':'美国短毛豚鼠','abyssinian-guinea-pig':'逆毛豚鼠','teddy-guinea-pig':'泰迪豚鼠','guinea-pig-pup':'豚鼠宝宝',
  'gray-chinchilla':'灰龙猫','beige-chinchilla':'米色龙猫','white-chinchilla':'白龙猫','black-velvet-chinchilla':'黑丝绒龙猫',
  'sable-ferret':'黑貂色雪貂','albino-ferret':'白化雪貂','cinnamon-ferret':'肉桂雪貂','panda-ferret':'熊猫雪貂',
  macaque:'猕猴','capuchin-monkey':'卷尾猴','golden-monkey':'金丝猴','baby-monkey':'猴宝宝',
  'yellow-chick':'黄绒小鸡','silkie-chick':'丝羽乌骨鸡','barred-rock-chick':'芦花鸡','buff-orpington-chick':'黄羽奥品顿鸡',
  'mallard-duck':'绿头鸭','pekin-duck':'北京鸭','muscovy-duck':'番鸭','yellow-duckling':'小黄鸭',
  'emperor-penguin':'帝企鹅','adelie-penguin':'阿德利企鹅','gentoo-penguin':'巴布亚企鹅','penguin-chick':'企鹅宝宝',
  'barn-owl':'仓鸮','snowy-owl':'雪鸮','great-horned-owl':'大角鸮','little-owl':'纵纹腹小鸮',
  'scarlet-macaw':'绯红金刚鹦鹉','blue-yellow-macaw':'蓝黄金刚鹦鹉','african-grey-parrot':'非洲灰鹦鹉',cockatiel:'玄凤鹦鹉',
  'greylag-goose':'灰雁','canada-goose':'加拿大黑雁','snow-goose':'雪雁','white-gosling':'小白鹅',
  'red-fox':'赤狐','arctic-fox':'北极狐','silver-fox':'银狐','fennec-fox':'耳廓狐',
  sky:'晴空',lilac:'浅丁香',solar:'暖阳',ember:'余烬',porcelain:'瓷白',peach:'蜜桃',
}
export function petPaletteName(id:string):string { return names[id] ?? getAvatarPalette(id).name }
